name: Developers Branch CI and Security checks

on:
  push:
    branches:
      - 'developer'
  pull_request:
    branches:
      - 'developer'
jobs:
  develop-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint pytest bandit

      - name: Lint code
        run: |
          pylint **/*.py || true