import { useMemo, useState } from 'react'
import { navigate, routes } from '../routes'

type UploadFile = {
  name: string
  url: string
}

type UploadResponse = {
  files?: UploadFile[]
  error?: string
}

function UploadsPage() {
  const role = useMemo(() => localStorage.getItem('plagchecker.role') || '', [])
  const adminUsername = useMemo(() => localStorage.getItem('plagchecker.username') || '', [])
  const [adminPassword, setAdminPassword] = useState('')
  const [files, setFiles] = useState<UploadFile[]>([])
  const [error, setError] = useState<string | null>(null)
  const [status, setStatus] = useState<string | null>(null)
  const apiBase =
    (import.meta.env.VITE_API_URL as string | undefined)?.replace(/\/$/, '') ||
    window.location.origin

  const fetchUploads = async () => {
    setError(null)
    setStatus(null)
    try {
      const res = await fetch(`${apiBase}/admin/uploads`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          admin_username: adminUsername,
          admin_password: adminPassword,
        }),
      })
      const data = (await res.json()) as UploadResponse
      if (!res.ok) {
        setError(data.error || 'Unable to load uploads.')
        return
      }
      setFiles(data.files || [])
      setStatus('Uploads loaded.')
    } catch {
      setError('Unable to reach the server.')
    }
  }

  if (role !== 'admin') {
    return (
      <div className="page">
        <div className="orb orb-one" aria-hidden="true" />
        <div className="orb orb-two" aria-hidden="true" />
        <header className="topbar">
          <button className="brand" type="button" onClick={() => navigate(routes.home)}>
            <span className="brand-mark">PC</span>
            <div>
              <p className="brand-title">Plag Checker</p>
              <p className="brand-subtitle">Admin access required</p>
            </div>
          </button>
        </header>
        <main className="content">
          <section className="panel">
            <p className="scan-error">You need an admin account to access this page.</p>
            <button className="submit" type="button" onClick={() => navigate(routes.auth)}>
              Go to login
            </button>
          </section>
        </main>
      </div>
    )
  }

  return (
    <div className="page">
      <div className="orb orb-one" aria-hidden="true" />
      <div className="orb orb-two" aria-hidden="true" />

      <header className="topbar">
        <button className="brand" type="button" onClick={() => navigate(routes.home)}>
          <span className="brand-mark">PC</span>
          <div>
            <p className="brand-title">Plag Checker</p>
            <p className="brand-subtitle">Uploaded scans</p>
          </div>
        </button>
        <button className="ghost-button" type="button" onClick={() => navigate(routes.admin)}>
          Back to admin
        </button>
      </header>

      <main className="content">
        <section className="intro">
          <h1>Uploaded files</h1>
          <p>Review PDF scans generated by the system.</p>
        </section>

        <section className="panel">
          <label className="field">
            <span>Admin password</span>
            <input
              type="password"
              value={adminPassword}
              onChange={(event) => setAdminPassword(event.target.value)}
              placeholder="••••••••"
            />
          </label>
          <div className="button-row">
            <button className="scan-button" type="button" onClick={fetchUploads}>
              Load uploads
            </button>
          </div>

          {status ? <p className="success">{status}</p> : null}
          {error ? <p className="scan-error">{error}</p> : null}

          <div className="uploads-list">
            {files.length ? (
              files.map((file) => (
                <a className="upload-link" key={file.name} href={file.url} target="_blank">
                  {file.name}
                </a>
              ))
            ) : (
              <p className="report-subtitle">No uploads yet.</p>
            )}
          </div>
        </section>
      </main>
    </div>
  )
}

export default UploadsPage
